Site redesign 2024
clubcapra/clubcapra.github.io pull request #103
Opened 2024-06-06 20:41 UTC by GLDuval

2024-06-06 21:48 UTC, patates-cipsi418 requested changes

2024-06-06 21:48 UTC, patates-cipsi418 commented on src/views/index.ts
> -  {
Idk if we should open an issue to add those pages later

2024-06-06 21:48 UTC, patates-cipsi418 commented on src/views/index.ts
> -  {
Idk if we should open an issue to add those pages later

2024-06-06 21:48 UTC, patates-cipsi418 commented on index.html
> +</html>
miss an ending return line

2024-06-06 21:48 UTC, patates-cipsi418 commented on src/components/SponsorCarouselComponent.vue
> +const sponsors = [
This should be get from a store

2024-06-06 21:48 UTC, patates-cipsi418 commented on src/views/PartnersView.vue
Should open an issue to have a store with the patrners

2024-06-06 22:22 UTC, patates-cipsi418 requested changes

2024-06-06 22:22 UTC, patates-cipsi418 commented on src/views/TeamView.vue
>  <script setup lang="ts">
Nicolas is no longer in admin

2024-06-07 19:26 UTC, GLDuval commented
@patates-cipsi418 Should be good now, I moved the partners and team members into new files in a `data` folder to make the views cleaner.

2024-06-07 19:26 UTC, GLDuval commented
Once approved we just need to make sure that we squash the commits and merge

2024-06-07 22:09 UTC, patates-cipsi418 approved these changes

2024-06-08 01:11 UTC, merged