Update section compétitions
clubcapra/clubcapra.github.io pull request #82
Opened 2024-02-07 05:13 UTC by nathan-gt

Ajout de sections Elrob&ENRICH + zwentendorf 2023 + modif section robocuprescue

2024-02-07 05:44 UTC, McCaroon commented
LGTM!
There only 1 picture that I might want to change. It's your call.

2024-02-07 20:06 UTC, Leuchak requested changes

2024-02-07 20:06 UTC, Leuchak commented on src/views/CompetitionView.vue
> +                <h2 class="mb-4">Enrich & Elrob</h2>
here, replace `&` with `&amp;`

2024-02-08 21:21 UTC, Leuchak approved these changes

2024-02-10 18:12 UTC, merged