Add translation for teams page
clubcapra/clubcapra.github.io pull request #91
Opened 2024-02-12 18:57 UTC by Flip-HH

- Added i18n definitions for english and french
- Replaced team member titles and programs using the new translation objects

Don't hesitate to comment if there are typos :/

2024-02-12 19:29 UTC, McCaroon commented on src/plugins/i18n.ts
> +    en: 'Captian',
Typo: captain *

2024-02-12 19:31 UTC, Flip-HH commented on src/plugins/i18n.ts
> +    en: 'Captian',
Fixed

2024-02-12 19:37 UTC, McCaroon commented
Function-wise, it looks good.
Text-wise, it looks good.
I'd just wait to see if @Leuchak has anything relevant to point out before merging, since web design isn't my forte. Good job! 👍

2024-02-12 22:26 UTC, AntoineMaltais commented on src/plugins/i18n.ts
> +    en: 'Captian',
bro didnt push his code

2024-02-12 22:42 UTC, AntoineMaltais approved these changes
lgtm(jai aussi tester)

2024-02-12 22:42 UTC, AntoineMaltais approved these changes
lgtm(j'ai tester aussi)

2024-02-12 22:51 UTC, AntoineMaltais requested changes

2024-02-12 22:51 UTC, AntoineMaltais commented on src/views/TeamView.vue
> +              "
revert this change its does the same thing and is longer

2024-02-12 22:52 UTC, AntoineMaltais approved these changes

2024-02-12 22:52 UTC, AntoineMaltais approved these changes

2024-02-12 22:59 UTC, Leuchak requested changes
As he said

2024-02-16 16:06 UTC, Flip-HH commented
> As he said

The change is necessary in this case, because the old method was checking if the string was undefined, then printing the other one. In the case where it is not undefined, it is simply printed to the html page.

When using the translation object, we need to check that the string is undefined before putting it in the object. If i simply added the $t around the string and left it as it was, the translation object tries to fetch a translation string based on the locale but since it's undefined, it doesn't work, which is why i changed the method to check that the string is undefined before doing the outputs.

2024-02-16 17:25 UTC, Leuchak approved these changes

2024-02-16 17:25 UTC, Leuchak commented
good

2024-02-16 17:26 UTC, merged